### ISSUE TITLE
Error: APK Signing Block offset < central directory offset.

### ISSUE THREAD

**Issue by WeiWenxing** [obfusk/apksigcopier#47]
Step:
1. apktool d  xxx.apk
2. apktool b -f xxx xxx_unsigned.apk
3. apksigcopier copy xxx.apk xxx_unsigned.apk xxx_signed.apk

and  error :
Error: APK Signing Block offset < central directory offset.

**Comment by obfusk** [comment]
`apksigcopier` requires the unsigned APKs to be identical (otherwise the v2/v3 signature will never be valid) and the signing process to be identical to that of `apksigner`.

So I'm pretty sure `apktool b` doesn't produce an identical unsigned APK; in this case, it seems to be smaller (maybe lack of padding somewhere?), hence the error.

**Comment by zt64** [comment]
I'm a little confused. So I took a system APK, modified a string in its resources and built it using apktool then copied the signature which lead to this error. Is there no way to make it work?

**Comment by obfusk** [comment]
> I'm a little confused. So I took a system APK, modified a string in its resources and built it using apktool then copied the signature which lead to this error. Is there no way to make it work?

If you **modify any part of the APK** -- whether it's any "string in its resources", ZIP metadata (ordering, timestamps, etc.), alignment/padding, etc. -- **the existing v2/v3 signature will never be valid**, regardless of whether you get an error during copying or not.

In this case you get an error because the APK is larger than the one from which the signature was copied from, so it can't insert the APK Signing Block at the required location since that offset is in the middle of the ZIP data (instead of right after the data, before the central directory). And no other location will ever produce a valid signature.

I don't know exactly what you're trying to do but I don't think there's any way to make it work.

**Comment by zt64** [comment]
That makes me wonder, how is it when the signature is available and the APK size changes then it's possible, such as in developing an app? I'm not too familiar with how APK signing works

**Comment by obfusk** [comment]
@zt64 https://source.android.com/docs/security/features/apksigning
